spring:
 application:
  name: SpringDemoProject
 datasource:
  url: jdbc:mysql://localhost:3306/sampleproject
  driver-class-name: com.mysql.cj.jdbc.Driver
  username: root
  password: lenin
 jpa:
  hibernate:
   ddl-auto: update
   show-sql: true